"""Extend student profile for ML features

Revision ID: 496d3340e156
Revises: b3003523e916
Create Date: 2026-02-08 18:37:52.259787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496d3340e156'
down_revision: Union[str, Sequence[str], None] = 'b3003523e916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('backlogs', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('attendance', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem1_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem2_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem3_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem4_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem5_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem6_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem7_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('sem8_gpa', sa.Float(), nullable=True))
    op.add_column('student_profiles', sa.Column('clubs', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('internship_domain', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('placement_domain', sa.String(), nullable=True))
    op.alter_column('student_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profiles', 'skills',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute("""
        ALTER TABLE student_profiles
        ALTER COLUMN placed_status
        TYPE BOOLEAN
        USING placed_status::boolean
    """)
    op.add_column(
        "student_profiles",
        sa.Column("clubs", sa.Text(), nullable=True)
    )

    op.drop_constraint(op.f('student_profiles_user_id_key'), 'student_profiles', type_='unique')
    op.drop_constraint(op.f('student_profiles_user_id_fkey'), 'student_profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('student_profiles_user_id_fkey'), 'student_profiles', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('student_profiles_user_id_key'), 'student_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.execute("""
        ALTER TABLE student_profiles
        ALTER COLUMN placed_status
        TYPE INTEGER
        USING placed_status::integer
    """)

    op.alter_column('student_profiles', 'skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('student_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_column("student_profiles", "clubs")
    op.drop_column('student_profiles', 'placement_domain')
    op.drop_column('student_profiles', 'internship_domain')
    op.drop_column('student_profiles', 'clubs')
    op.drop_column('student_profiles', 'sem8_gpa')
    op.drop_column('student_profiles', 'sem7_gpa')
    op.drop_column('student_profiles', 'sem6_gpa')
    op.drop_column('student_profiles', 'sem5_gpa')
    op.drop_column('student_profiles', 'sem4_gpa')
    op.drop_column('student_profiles', 'sem3_gpa')
    op.drop_column('student_profiles', 'sem2_gpa')
    op.drop_column('student_profiles', 'sem1_gpa')
    op.drop_column('student_profiles', 'attendance')
    op.drop_column('student_profiles', 'backlogs')
    op.drop_column('student_profiles', 'age')
    # ### end Alembic commands ###
