"""add ml scores to applications

Revision ID: 808447d24e36
Revises: 496d3340e156
Create Date: 2026-03-16 23:00:02.217743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808447d24e36'
down_revision: Union[str, Sequence[str], None] = '496d3340e156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('placement_probability', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('job_fit', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('domain_alignment', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('readiness_category', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('applied_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'applied_at')
    op.drop_column('applications', 'status')
    op.drop_column('applications', 'readiness_category')
    op.drop_column('applications', 'domain_alignment')
    op.drop_column('applications', 'job_fit')
    op.drop_column('applications', 'placement_probability')
    op.drop_column('applications', 'match_score')
    # ### end Alembic commands ###
